site_name: AS207960 Docs
site_author: AS207960
site_url: https://docs.as207960.net

copyright: Copyright &copy; 2020 AS207960 Cyfyngedig

theme:
  name: material
  logo: https://as207960.net/img/logo.png

palette:
  primary: black
  accent: black

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/as207960
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/as_207960

plugins:
  - search:
      prebuild_index: true
  - git-revision-date-localized
  - minify:
        minify_html: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

