site_name: Glauca Docs
site_author: Glauca / AS207960
site_url: https://docs.glauca.digital
site_description: Documentation on Glauca / AS207960 services

copyright: Copyright &copy; 2020 AS207960 Cyfyngedig, trading as Glauca

theme:
  name: material
  favicon: https://as207960.net/favicon.svg
  logo: https://as207960.net/assets/img/logo.svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/as207960
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GlaucaDigital

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      prebuild_index: true
  - awesome-pages
  - git-revision-date-localized
  - minify:
        minify_html: true

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

